name: SonarCloud

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 22
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
    - name: npm install, lint, and test
      run: |
        npm ci
        npm run lint:report
        npm test
      env:
        CI: true
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
